

services:

  # 1. SENSORES DE RED
  zeek:
    # Ajustamos la ruta de construcción porque moviste la carpeta zeek_custom
    build: ./config/zeek/zeek_custom
    container_name: siem_zeek
    network_mode: "host"
    privileged: true
    environment:
      - INTERFACE=any
    volumes:
      # Ajustamos la ruta de los logs
      - ./logs/logs_zeek:/pcap
    restart: always

  snort:
    build: ./snort_core
    container_name: siem_snort
    network_mode: "host"
    privileged: true
    volumes:
      # Ajustamos ruta de logs y de configuración
      - ./logs/logs_snort:/var/log/snort
      - ./config/snort/snort_config:/etc/snort
    # Comando ajustado (nota: verifica que tu interfaz sea wlp2s0, si no, cámbiala aquí)
    command: snort -q -i wlp2s0 -A fast -c /etc/snort/snort.conf -l /var/log/snort -k none
    restart: always

  # 2. TRANSPORTE
  redis:
    image: redis:alpine
    container_name: siem_redis
    ports:
      - "6379:6379"
    restart: always

  # 3. BASE DE DATOS
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: siem_elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: always

  # 4. CEREBRO INTELIGENTE (MATRIZ)
  cerebro:
    build: ./python_core
    container_name: siem_cerebro
    volumes:
      - ./python_core:/app
      # Ajustamos las rutas para que el cerebro encuentre los logs
      - ./logs/logs_zeek:/app/logs_zeek
      - ./logs/logs_snort:/app/logs_snort
    environment:
      - REDIS_HOST=redis
      - ELASTIC_HOST=elasticsearch
    depends_on:
      - redis
      - elasticsearch
    restart: always

  # 5. DASHBOARD
  dashboard:
    image: python:3.9-slim
    container_name: siem_dashboard
    working_dir: /app
    volumes:
      - ./mi_dashboard:/app
    command: >
      sh -c "pip install --upgrade pip &&
             pip install streamlit redis pandas elasticsearch plotly &&
             streamlit run app.py"
    ports:
      - "8501:8501"
    depends_on:
      - redis
      - elasticsearch
    restart: always

volumes:
  elastic_data:
